### ISSUE TITLE
[Suggestion]Detect Radiation on an location using RFTools Control

### ISSUE THREAD

**Issue by Susjin** [McJtyMods/DeepResonance#126]
I was playing with RFTools Control and i want to make an system that will turn off the generator from Deep Resonance when the area reach an certain radiation, but the opcode to detect radiation does not exist, and would be awesome to add that opcode

**Comment by McJty** [comment]
That's a good idea. I will add something like that

**Comment by Xandaros** [comment]
I wanted to expose functionality like this in the OC interface, as well, but couldn't figure out a good way to do it.
If you can think of something, that might be nice, as well.
