### ISSUE TITLE
No way to remove debug_block's from /drgen showradiation command

### ISSUE THREAD

**Issue by Colonel-Rogue** [McJtyMods/DeepResonance#144]
There doesn't appear to be a way to remove the debug blocks generated by this command, which is a bit of a problem seeing as they're actual blocks and get in the way of everything and there's a gigantic sphere with a radius of about 20 in a section of my server.

**Comment by McJty** [comment]
I think you have to do a new showradiation with a level very high so that nothing matches. Or very low. Don't remember. One of those ;-)

**Comment by Colonel-Rogue** [comment]
And _hypothetically_ if it hit the skybox . . . *cough*

**Comment by Sentrus** [comment]
Neither of those things works McJty. Once you've created the debug blocks, they are there.

**Comment by Dridus** [comment]
for me `/drgen showradiation -1` worked
