### ISSUE TITLE
Incompatible with Velocity

### ISSUE THREAD

**Issue by astei** [McJtyMods/DeepResonance#271]
I am running Forge 2739, Direwolf20 modpack (2.2.0), and the latest version of [Velocity](https://github.com/VelocityPowered/Velocity).

Here's the stacktrace I got when logging into the server after switching between my lobby server (running DW20) to another (also running DW20): https://paste.ubuntu.com/p/Yyn4bB6s5C/

**Comment by josephcsible** [comment]
Please report this to Velocity.

**Comment by astei** [comment]
But I _am_ the author of Velocity, and I'm fairly certain this is an issue in Deep Resonance, not Velocity. Velocity doesn't do anything crazy to support Forge aside from sending the Join Game packet multiple times and resetting the FML handshake.

**Comment by McJty** [comment]
How is this a problem on our side? It is up to plugins to make sure they don't break vanilla and/or mods. Mods cannot cater for all possible plugins out there. Besides, i would not even know how to cater for this or fix this. The code is not doing anything wrong as far as I can see.

**Comment by McJty** [comment]
Hold on. Seems to be our side anyway

**Comment by McJty** [comment]
Fixed upcoming release
