### ISSUE TITLE
Russian manual Deep Resonance

### ISSUE THREAD

**Issue by kellixon** [McJtyMods/DeepResonance#278]
MC 1.12.2. DeepResonance 1.7.5.
-To use it, replace the file with "assets/deepresonance/text/manual.txt"
-Для использования, заменить файл по пути "assets/deepresonance/text/manual.txt"
[manual.txt](https://github.com/McJtyMods/DeepResonance/files/2885809/manual.txt)

**Comment by McJty** [comment]
Merged
